In [ ]:
#result anlysis
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from tensorflow.keras import models

In [ ]:
model=models.load_model('./models/timeseries_model.h5')
x_test = np.load('./test/waveform_testset/x_test.npy')
y_test = np.load('./test/waveform_testset/y_test.npy')

classes = model.predict(x_test, batch_size=120)
lis=np.zeros(classes.shape[0])

for i in range(classes.shape[0]):
 jeg = np.where(classes[i,:] == max(classes[i,:]))
 lis[i] = jeg[0]

tru=np.zeros(classes.shape[0])
s1=123
s2=125
s3=72
s4=108
tru[:s1] = 0
tru[s1:s1+s2] = 1
tru[s1+s2:s1+s2+s3] = 2
tru[s1+s2+s3:s1+s2+s3+s4] = 3

target = ['earthquake','rockfall','micro-earthquake','enviroemnt noise']
print(classification_report(tru, lis, target_names=target))
print(confusion_matrix(tru, lis))

                  precision    recall  f1-score   support

      earthquake       0.90      0.99      0.94       123
        rockfall       0.89      0.98      0.94       125
micro-earthquake       0.96      0.74      0.83        72
enviroemnt noise       0.86      0.79      0.82       108

        accuracy                           0.89       428
       macro avg       0.90      0.87      0.88       428
    weighted avg       0.90      0.89      0.89       428

[[122   0   0   1]
 [  0 123   0   2]
 [  3   5  53  11]
 [ 11  10   2  85]]


In [ ]:
model=models.load_model('./models/STFT_model.h5')
x_test = np.load('./test/STFT_testset/x_test.npy')
y_test = np.load('./test/STFT_testset/y_test.npy')

classes = model.predict(x_test, batch_size=120)
lis=np.zeros(classes.shape[0])

for i in range(classes.shape[0]):
 jeg = np.where(classes[i,:] == max(classes[i,:]))
 lis[i] = jeg[0]

tru=np.zeros(classes.shape[0])
s1=123
s2=125
s3=72
s4=108
tru[:s1] = 0
tru[s1:s1+s2] = 1
tru[s1+s2:s1+s2+s3] = 2
tru[s1+s2+s3:s1+s2+s3+s4] = 3

target = ['earthquake','rockfall','micro-earthquake','enviroemnt noise']
print(classification_report(tru, lis, target_names=target))
print(confusion_matrix(tru, lis))

                  precision    recall  f1-score   support

      earthquake       0.97      0.98      0.97       123
        rockfall       0.96      0.90      0.93       125
micro-earthquake       0.82      0.76      0.79        72
enviroemnt noise       0.79      0.88      0.83       108

        accuracy                           0.89       428
       macro avg       0.88      0.88      0.88       428
    weighted avg       0.90      0.89      0.89       428

[[120   0   1   2]
 [  0 112   3  10]
 [  2   2  55  13]
 [  2   3   8  95]]


In [ ]:
model=models.load_model('./models/CWT_model.h5')
x_test = np.load('./test/CWT_testset/x_test.npy')
y_test = np.load('./test/CWT_testset/y_test.npy')

classes = model.predict(x_test, batch_size=120)
lis=np.zeros(classes.shape[0])

for i in range(classes.shape[0]):
 jeg = np.where(classes[i,:] == max(classes[i,:]))
 lis[i] = jeg[0]

tru=np.zeros(classes.shape[0])
s1=123
s2=125
s3=72
s4=108
tru[:s1] = 0
tru[s1:s1+s2] = 1
tru[s1+s2:s1+s2+s3] = 2
tru[s1+s2+s3:s1+s2+s3+s4] = 3

target = ['earthquake','rockfall','micro-earthquake','enviroemnt noise']
print(classification_report(tru, lis, target_names=target))
print(confusion_matrix(tru, lis))

                  precision    recall  f1-score   support

      earthquake       0.98      0.98      0.98       123
        rockfall       0.92      0.93      0.92       125
micro-earthquake       0.88      0.72      0.79        72
enviroemnt noise       0.81      0.89      0.85       108

        accuracy                           0.90       428
       macro avg       0.90      0.88      0.89       428
    weighted avg       0.90      0.90      0.90       428

[[121   1   1   0]
 [  1 116   1   7]
 [  1   3  52  16]
 [  1   6   5  96]]
