In [3]:
import scipy.io as io
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import keras

In [4]:
#load data and model
x_test_series_mat = io.loadmat('x_test_series.mat')
x_test_series = x_test_series_mat['x_test_series']
model = keras.models.load_model('series_model.h5')

In [5]:
#result anlysis

classes = model.predict(x_test_series, batch_size=12)
lis=np.zeros(classes.shape[0])

for i in range(classes.shape[0]):
 jeg = np.where(classes[i,:] == max(classes[i,:]))
 lis[i] = jeg[0]

#testing labels
s1=116 #seism
s2=70 #quake
s3=120 #rock
s4=105 #noise
tru=np.zeros(classes.shape[0])
tru[:s1] = 0
tru[s1:s1+s2] = 1
tru[s1+s2:s1+s2+s3] = 2
tru[s1+s2+s3:s1+s2+s3+s4] = 3

from sklearn.metrics import classification_report
target = ['earthquake','micro-earthquake','rockfall','enviroemnt noise']
print(classification_report(tru, lis, target_names=target))
print(confusion_matrix(tru, lis))

                  precision    recall  f1-score   support

      earthquake       0.95      0.92      0.93       116
micro-earthquake       0.84      0.74      0.79        70
        rockfall       0.91      0.92      0.91       120
enviroemnt noise       0.78      0.86      0.82       105

        accuracy                           0.87       411
       macro avg       0.87      0.86      0.86       411
    weighted avg       0.88      0.87      0.87       411

[[107   0   0   9]
 [  3  52   4  11]
 [  1   4 110   5]
 [  2   6   7  90]]
