In [14]:
import scipy.io as io
import numpy as np
import utlis.utils as utils
#load time series data
x_test_series_mat = io.loadmat('./data/testset/x_test_series.mat')
x_test_series = x_test_series_mat['x_test_series_raw']
#load labels
#earthqauke [1,0,0,0]
#quake [0,1,0,0]
#rockfall [0,0,1,0]
#other noise [0,0,0,1]
y_test = np.load('./data/testset/y_test.npy')

In [15]:
# Load pre-trained model
from tensorflow.keras import models
model=models.load_model('./models/multi_channel/time_model_multi.h5')
# Prediction
classes = model.predict(x_test_series, batch_size=256)

4/4 [==============================] - 4s 992ms/step


In [16]:
# Results
utils.resultshow(classes,y_test)

                  precision    recall  f1-score   support

      earthquake       0.98      0.99      0.99       116
           quake       0.87      0.87      0.87        70
        rockfall       0.91      0.89      0.90       120
enviroemnt noise       0.86      0.87      0.86       105

        accuracy                           0.91       411
       macro avg       0.90      0.91      0.91       411
    weighted avg       0.91      0.91      0.91       411

[[115   0   0   1]
 [  1  61   4   4]
 [  0   3 107  10]
 [  1   6   7  91]]
